services:
    _defaults:
        public: true

    CoreShop\Bundle\MessengerBundle\Menu\IndexMenuBuilder:
        tags:
            - { name: 'coreshop.menu', type: messenger, menu: messenger }

    CoreShop\Bundle\MessengerBundle\EventListener\AdminJavascriptListener:
        arguments:
            - '@router'
        tags:
            - { name: kernel.event_subscriber }
