coreshop_admin_messenger_count:
  path: /admin/messenger/count
  defaults: { _controller: CoreShop\Bundle\MessengerBundle\Controller\ListMessagesController::listReceiverMessageCountAction }
  options:
    expose: true

coreshop_admin_messenger_list_failed:
  path: /admin/messenger/list-failed/{receiverName}
  defaults: { _controller: CoreShop\Bundle\MessengerBundle\Controller\ListMessagesController::listFailedMessagesAction }
  options:
    expose: true

coreshop_admin_messenger_list:
  path: /admin/messenger/list/{receiverName}
  defaults: { _controller: CoreShop\Bundle\MessengerBundle\Controller\ListMessagesController::listMessagesAction }
  options:
    expose: true

coreshop_admin_messenger_list_failure_receivers:
  path: /admin/messenger/list-failure-receivers
  defaults: { _controller: CoreShop\Bundle\MessengerBundle\Controller\ListMessagesController::listFailureReceiversAction }
  options:
    expose: true

coreshop_admin_messenger_delete:
  path: /admin/messenger/delete/{receiverName}
  defaults: { _controller: CoreShop\Bundle\MessengerBundle\Controller\MessageController::deleteStoredMessageAction }
  methods: 'DELETE'
  options:
    expose: true

coreshop_admin_messenger_retry:
  path: /admin/messenger/retry/{receiverName}
  defaults: { _controller: CoreShop\Bundle\MessengerBundle\Controller\MessageController::retryFailedMessageAction }
  methods: 'POST'
  options:
    expose: true
